spring.application.name=covira-backend

# ==========================
# DATABASE
# ==========================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/covira_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=Senzo@9610

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# ==========================
# CORS / DEMO DATA
# ==========================
covira.demo-data.enabled=${COVIRA_DEMO_DATA:false}

# ==========================
# EMAIL CONFIGURATION
# ==========================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
